apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: quantpulse

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: quantpulse-backend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:

            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: quantpulse-config
                  key: APP_NAME

            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: quantpulse-config
                  key: APP_VERSION

            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: quantpulse-config
                  key: ENVIRONMENT

            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: quantpulse-config
                  key: DEBUG

            - name: DATABASE_URL
              value: "postgresql://quantpulse:quantpulse123@postgres:5432/quantpulse"

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: quantpulse-secret
                  key: JWT_SECRET_KEY

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10