apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana
  namespace: quantpulse

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.2.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin

            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin123

          volumeMounts:
            - name: grafana-dashboard
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.json
              subPath: dashboard.json

            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.yaml
              subPath: dashboard.yaml

            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
              subPath: prometheus.yaml

          readinessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15

      volumes:
        - name: grafana-dashboard
          configMap:
            name: grafana-dashboard

        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: grafana-datasource
          configMap:
            name: grafana-datasource