apiVersion: v1
kind: Service

metadata:
  name: redis
  namespace: quantpulse

spec:
  selector:
    app: redis

  ports:
    - name: redis
      port: 6379
      targetPort: 6379

    - name: http-metrics
      port: 9121
      targetPort: 9121
