apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-config
  namespace: quantpulse

data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:

      - job_name: "quantpulse-backend"

        metrics_path: /metrics

        static_configs:
          - targets:
              - backend:8000