apiVersion: v1
kind: ConfigMap

metadata:
  name: quantpulse-config
  namespace: quantpulse

data:

  APP_NAME: QuantPulse

  APP_VERSION: "1.0.0"

  ENVIRONMENT: production

  DEBUG: "False"

  POSTGRES_HOST: postgres

  POSTGRES_PORT: "5432"

  POSTGRES_DB: quantpulse

  POSTGRES_USER: quantpulse

  PROMETHEUS_PORT: "9090"

  GRAFANA_PORT: "3000"