apiVersion: v1
kind: Secret

metadata:
  name: quantpulse-secret
  namespace: quantpulse

type: Opaque

stringData:

  POSTGRES_PASSWORD: quantpulse123

  JWT_SECRET_KEY: quantpulse-super-secret-key-change-before-production